# syntax=docker/dockerfile:1.7
# ---------------------------------------------------------------------------
# TaskFlow API - production image
#  * multi-stage: dev tooling never reaches the runtime image
#  * runs as the unprivileged "node" user, application files owned by root (read-only for the app)
#  * npm/yarn removed from the runtime layer (not needed at runtime, and they are a
#    frequent source of HIGH CVEs reported by Trivy)
#  * OCI labels make every image traceable to its commit and Jenkins build
# ---------------------------------------------------------------------------
ARG NODE_VERSION=22

FROM node:${NODE_VERSION}-alpine AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --omit=dev --ignore-scripts --no-audit --no-fund && npm cache clean --force

FROM node:${NODE_VERSION}-alpine AS runtime
ARG APP_VERSION=dev
ARG GIT_COMMIT=local
ARG BUILD_NUMBER=dev
ARG BUILD_DATE=unknown
ARG SOURCE_URL=https://github.com/paul-ab2/taskflow-devops

LABEL org.opencontainers.image.title="taskflow-api" \
      org.opencontainers.image.description="TaskFlow task management REST API" \
      org.opencontainers.image.version="${APP_VERSION}" \
      org.opencontainers.image.revision="${GIT_COMMIT}" \
      org.opencontainers.image.created="${BUILD_DATE}" \
      org.opencontainers.image.source="${SOURCE_URL}" \
      com.taskflow.jenkins.build="${BUILD_NUMBER}"

# Patch OS packages and strip package managers that are not needed at runtime.
RUN apk upgrade --no-cache \
 && rm -rf /usr/local/lib/node_modules/npm /usr/local/lib/node_modules/corepack \
           /usr/local/bin/npm /usr/local/bin/npx /usr/local/bin/corepack \
           /opt/yarn* /usr/local/bin/yarn /usr/local/bin/yarnpkg

ENV NODE_ENV=production \
    PORT=3000 \
    APP_VERSION=${APP_VERSION} \
    GIT_COMMIT=${GIT_COMMIT} \
    BUILD_NUMBER=${BUILD_NUMBER}

WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
# build-info.json is generated by `npm run build`; the glob makes it optional for local builds.
COPY package.json build-info.jso[n] ./
COPY src ./src
COPY public ./public

USER node
EXPOSE 3000

HEALTHCHECK --interval=10s --timeout=3s --start-period=5s --retries=3 \
  CMD ["node", "-e", "fetch('http://127.0.0.1:3000/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"]

CMD ["node", "src/server.js"]
