#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# One-command setup of the whole DevOps platform on a laptop (macOS/Linux).
#
#   ./scripts/bootstrap.sh https://github.com/<you>/taskflow-devops.git [github-user] [github-token]
#
# 1. generates infra/.env with random secrets (never committed)
# 2. starts SonarQube, waits for it, creates the quality gate + analysis token
# 3. builds the custom Jenkins image and starts every service
# 4. prints the URLs and credentials
# Re-running is safe: existing secrets and tokens are kept.
# Works with the bash 3.2 that ships with macOS (no jq needed on the host).
# ---------------------------------------------------------------------------
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
INFRA="$ROOT/infra"
ENV_FILE="$INFRA/.env"

REPO_URL="${1:-}"
GH_USER="${2:-none}"
GH_TOKEN="${3:-none}"

info() { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
fail() { printf '\033[1;31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }

command -v docker >/dev/null || fail "Docker is not installed (install Docker Desktop)"
docker info >/dev/null 2>&1 || fail "Docker is not running - start Docker Desktop first"
command -v openssl >/dev/null || fail "openssl is required"

rand() { openssl rand -base64 48 | tr -dc 'A-Za-z0-9' | cut -c1-"${1:-32}"; }

set_env() { # set_env KEY VALUE  (portable in-place edit, works with BSD sed)
  local key="$1" value="$2" tmp
  tmp="$(mktemp)"
  grep -v "^${key}=" "$ENV_FILE" > "$tmp" || true
  echo "${key}=${value}" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
}

get_env() { grep "^$1=" "$ENV_FILE" 2>/dev/null | head -1 | cut -d= -f2- ; }

# ---------------------------------------------------------------- 1. secrets
if [ ! -f "$ENV_FILE" ]; then
  [ -n "$REPO_URL" ] || fail "first run needs your GitHub repo URL: ./scripts/bootstrap.sh https://github.com/<you>/taskflow-devops.git"
  info "Generating $ENV_FILE with random secrets"
  cat > "$ENV_FILE" <<EOF
# Generated by scripts/bootstrap.sh on $(date) - DO NOT COMMIT
GIT_REPO_URL=${REPO_URL}
GITHUB_USER=${GH_USER}
GITHUB_TOKEN=${GH_TOKEN}
JENKINS_ADMIN_ID=admin
JENKINS_ADMIN_PASSWORD=$(rand 20)
SONAR_ADMIN_PASSWORD=Sonar-$(rand 16)-9x!
SONAR_DB_PASSWORD=$(rand 24)
SONAR_TOKEN=
STAGING_JWT_SECRET=$(rand 48)
PROD_JWT_SECRET=$(rand 48)
CHAOS_TOKEN=$(rand 32)
GRAFANA_ADMIN_PASSWORD=$(rand 20)
EOF
  chmod 600 "$ENV_FILE"
else
  info "Reusing existing $ENV_FILE"
  [ -n "$REPO_URL" ] && set_env GIT_REPO_URL "$REPO_URL"
  [ "$GH_USER" != "none" ] && set_env GITHUB_USER "$GH_USER"
  [ "$GH_TOKEN" != "none" ] && set_env GITHUB_TOKEN "$GH_TOKEN"
fi

compose() { docker compose --env-file "$ENV_FILE" -f "$INFRA/docker-compose.yml" "$@"; }

# ---------------------------------------------------------------- 2. SonarQube
info "Starting SonarQube (first start takes 1-3 minutes)"
compose up -d sonar-db sonarqube

printf 'Waiting for SonarQube'
for _ in $(seq 1 90); do
  if curl -fsS http://localhost:9000/api/system/status 2>/dev/null | grep -q '"status":"UP"'; then
    echo " - UP"; break
  fi
  printf '.'; sleep 5
done
curl -fsS http://localhost:9000/api/system/status | grep -q '"status":"UP"' || fail "SonarQube did not start - check: docker logs sonarqube"

if [ -z "$(get_env SONAR_TOKEN)" ]; then
  SONAR_ADMIN_PASSWORD="$(get_env SONAR_ADMIN_PASSWORD)" "$ROOT/scripts/sonar-setup.sh" > "$INFRA/.sonar-setup.log"
  TOKEN="$(grep '^SONAR_TOKEN=' "$INFRA/.sonar-setup.log" | cut -d= -f2-)"
  [ -n "$TOKEN" ] || { cat "$INFRA/.sonar-setup.log"; fail "could not create SonarQube token"; }
  set_env SONAR_TOKEN "$TOKEN"
  grep -v '^SONAR_TOKEN=' "$INFRA/.sonar-setup.log" || true
  rm -f "$INFRA/.sonar-setup.log"
else
  info "SonarQube token already present - skipping SonarQube setup"
fi

# ---------------------------------------------------------------- 3. everything else
info "Building Jenkins image and starting the platform"
compose up -d --build

printf 'Waiting for Jenkins'
for _ in $(seq 1 60); do
  code="$(curl -s -o /dev/null -w '%{http_code}' http://localhost:8080/login || true)"
  if [ "$code" = "200" ]; then echo " - UP"; break; fi
  printf '.'; sleep 5
done

cat <<EOF

$(printf '\033[1;32m')Platform is ready$(printf '\033[0m')

  Jenkins       http://localhost:8080   user: admin   password: $(get_env JENKINS_ADMIN_PASSWORD)
  SonarQube     http://localhost:9000   user: admin   password: $(get_env SONAR_ADMIN_PASSWORD)
  Grafana       http://localhost:3000   user: admin   password: $(get_env GRAFANA_ADMIN_PASSWORD)
  Prometheus    http://localhost:9090
  Alertmanager  http://localhost:9093
  Mailpit       http://localhost:8025   (team inbox for alert e-mails)
  Registry      http://localhost:5001/v2/_catalog

  After the first pipeline run:
  Staging       http://localhost:8001
  Production    http://localhost:8000

Next: open Jenkins -> "TaskFlow CI/CD Pipeline" -> Build with Parameters -> Build
(credentials are stored in infra/.env)
EOF
